"$schema" = "https://starship.rs/config-schema.json"

format = """
[](fg:#89b4fa)\
$os\
$username\
[](fg:#89b4fa bg:#74c7ec)\
$directory\
[](fg:#74c7ec bg:#a6e3a1)\
$git_branch\
$git_status\
[](fg:#a6e3a1 bg:#f9e2af)\
$java\
$nodejs\
$python\
$golang\
$rust\
[](fg:#f9e2af bg:#cba6f7)\
$docker_context\
$kubernetes\
[](fg:#cba6f7)\
$line_break\
$character"""

[os]
disabled = false
style = "bg:#89b4fa fg:#1e1e2e"

[os.symbols]
Macos = " "
Linux = " "
Windows = "󰍲 "

[username]
show_always = true
style_user = "bg:#89b4fa fg:#1e1e2e"
style_root = "bg:#89b4fa fg:#1e1e2e"
format = "[$user ]($style)"

[directory]
style = "bg:#74c7ec fg:#1e1e2e"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = ".../"

[git_branch]
symbol = ""
style = "bg:#a6e3a1 fg:#1e1e2e"
format = "[ $symbol $branch ]($style)"

[git_status]
style = "bg:#a6e3a1 fg:#1e1e2e"
format = "[$all_status$ahead_behind ]($style)"

[java]
symbol = ""
style = "bg:#f9e2af fg:#1e1e2e"
format = "[ $symbol $version ]($style)"

[nodejs]
symbol = ""
style = "bg:#f9e2af fg:#1e1e2e"
format = "[ $symbol $version ]($style)"

[python]
symbol = ""
style = "bg:#f9e2af fg:#1e1e2e"
format = "[ $symbol $version ]($style)"

[golang]
symbol = ""
style = "bg:#f9e2af fg:#1e1e2e"
format = "[ $symbol $version ]($style)"

[rust]
symbol = ""
style = "bg:#f9e2af fg:#1e1e2e"
format = "[ $symbol $version ]($style)"

[docker_context]
symbol = ""
style = "bg:#cba6f7 fg:#1e1e2e"
format = "[ $symbol $context ]($style)"

[kubernetes]
disabled = false
symbol = "󱃾"
style = "bg:#cba6f7 fg:#1e1e2e"
format = "[ $symbol $context ]($style)"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
